version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  workout-planner:
    build: . 
    # ports:
    #   - "3000:3000"
    image: 2kshine/workout-planner
    environment:
      - PORT=3000
    depends_on:
      - redis

  redis:
    image: redis


      
