version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  workout-planner:
    build: . 
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - redis
    env_file:
      - ./.env

  redis:
    image: redis


      
